spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: hy342698

mybatis:
  configuration:
    map-underscore-to-camel-case: true #?????????????????